apiVersion: apps/v1 
kind: Deployment
metadata:
  name: itday28-deployment
spec:
  selector:
    matchLabels:
      app: itday28-rest
  replicas: 1 
  template:
    metadata:
      labels:
        app: itday28-rest
    spec:
      containers:
      - name: day28rest
        image: darwin0616/itday28-rest:v8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: itday28-deployment
spec:
  type: NodePort
  selector:
    app: itday28-rest
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
